        ; file: CCDLOAD.INI
        ; IGA hardware (chip and controller) parameters
1       ; IGA Number
          
1     ; IGA Chip Type 1 = Std 2 Mux
        ;               2 = Std 4 Mux
        ;               101 = 2 Mux with special pixel ordering
        ; Number of pixels
1024    ; total_active_x_pixels (in the horizontal direction)
1       ; total_active_y_pixels (in the vertical direction)
4       ; number_serial_pxls_before_active_area
4       ; number_serial_pxls_after_active_area
17      ; number of clocks before readout
400     ; number of clocks in idle for expose

5       ; readout register location and direction
        ; add one from each of the following:
        ;       register location =     0       left
        ;                               1       top
        ;                               2       right
        ;                               3       bottom
        ;
        ; direction is relative to our standard configuration
        ; with the readout register in the left position
        ;       direction         =     0       top to bottom
        ;                               4       bottom to top
        ;
        ;
        ;   ^                                                                */
        ;   |
        ;   *______       *******->     ______         _____ 
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *  0  |       |  1  |       |  2  *       |   3 |
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *_____|       |_____|       |_____*     <-*******
        ;                                     |              
        ;                                     V              
        ;                
        ;                                                    
        ;                                     ^                                      
        ;                                     |    
        ;    ______     <-*******       ______*       ______ 
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *  4  |       |   5 |       |  6  *       |  7  |
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *     |       |     |       |     *       |     |
        ;   *_____|       |_____|       |_____*       *******->
        ;   |                    
        ;   V                    
        ;
        ;                
        ; Limit checking for driver calls
0       ; Minimum temperature in degrees K
300     ; Maximum temperature in degrees K

3               ; Minimum shutter time in milliseconds
400000000       ; Maximum shutter time in milliseconds

0       ; Minimum Gain
4       ; Maximum Gain

        ; Returned in driver call. Currently not used by the driver.
        ; pixel spacing/size in tenths of um
250    ;       horizontally
250    ;       vertically

1       ; # ExtraSkipPixels
0       ; CorrectionMode 0 = None; 1 = Value; 2 = Average
0       ; Value or NumToAverage
1       ; NumOfBadPixels
492 1   ; FirstBadPixel

